version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.backend
    container_name: sketch-backend
    env_file:
      - ./packages/db/.env
      - ./apps/http-server/.env
    ports:
      - 3001:3001

  websocket:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.websocket
    container_name: sketch-websocket
    env_file:
      - ./packages/db/.env
      - ./apps/ws-server/.env
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend
      args:
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_WS_BASE_URL=${NEXT_PUBLIC_WS_BASE_URL}
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_FE_URL=${NEXT_PUBLIC_FE_URL}
    container_name: sketch-frontend

    env_file:
      - ./packages/db/.env
      - ./apps/frontend/.env
    ports:
      - 3000:3000
