FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml pnpm-workspace.yaml
COPY ./turbo.json  ./turbo.json

COPY ./apps/http-server  ./apps/http-server

RUN pnpm install
RUN pnpm run db:generate
RUN pnpm run build

CMD ["pnpm", "run", "start:backend"]