FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml  ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

COPY ./apps/frontend ./apps/frontend

RUN pnpm install
RUN pnpm run db:generate
RUN pnpm run build

CMD ["pnpm", "run", "start:frontend"]

