import type { Metadata } from "next";

import { Geist, Geist_Mono, Architects_Daughter } from "next/font/google";

import {
  Fira_Code,
  Nunito,
  Comic_Relief,
  Permanent_Marker,
} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "./theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const architects = Architects_Daughter({
  variable: "--font-architect",
  subsets: ["latin"],
  weight: "400",
});
const code = Fira_Code({
  variable: "--font-code",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});
const marker = Permanent_Marker({
  variable: "--font-marker",
  subsets: ["latin"],
  weight: "400",
});

const comic = Comic_Relief({
  variable: "--font-comic",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` bg-white dark:bg-black/80 ${geistSans.variable} ${marker.variable} ${geistMono.variable} ${comic.variable} ${nunito.variable}  ${architects.variable} ${code.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
