import type { Metadata } from "next";

import { Geist, Geist_Mono, Architects_Daughter } from "next/font/google";

import {
  Fira_Code,
  Nunito,
  Comic_Relief,
  Permanent_Marker,
} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const architects = Architects_Daughter({
  variable: "--font-architect",
  subsets: ["latin"],
  weight: "400",
});
const code = Fira_Code({
  variable: "--font-code",
  subsets: ["latin"],
});

const inter = Nunito({
  variable: "--font-inter",
  subsets: ["latin"],
});
const marker = Permanent_Marker({
  variable: "--font-marker",
  subsets: ["latin"],
  weight: "400",
});

const comic = Comic_Relief({
  variable: "--font-comic",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${architects.variable} ${code.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
